[CN] Another batch of tidying
rems-project/cerberus pull request #355
Opened 2024-06-27 19:11 UTC by bcpierce00

2024-06-27 19:52 UTC, thatplguy commented on backend/cn/ONBOARDING.md
> +### Entry Points:
Lines 56–76 are duplicated on lines 80–100.  Is this intentional?

2024-06-28 01:58 UTC, bcpierce00 commented on backend/cn/ONBOARDING.md
> +### Entry Points:
No -- probably a result of some rebasing silliness...

2024-06-28 13:29 UTC, dc-mak requested changes
Main things are rebasing (and squashing) and the SymSet incantation. Otherwise rest looks good.

2024-06-28 13:29 UTC, dc-mak commented on backend/cn/mucore.mli
> +  end
`module SymSet : Set.S with type elt = Sym.t and type t = Set.Make(Sym).t`
The trick is the `and` otherwise you're just doing something like 
`module SymSet : Set.S with type elt = Sym.t ;; type t = Set.Make(Sym).t`

You were very close, and I was very confused. I had to check the [OCaml manual to get the grammar](https://ocaml.org/manual/5.2/modtypes.html#module-type), and even then it took a few tries for me to figure it out 😅

2024-06-28 13:29 UTC, dc-mak commented on backend/cn/README.md
I think the merge went wrong. This should remain.

2024-06-28 13:29 UTC, dc-mak commented on backend/cn/ONBOARDING.md
> +- change all filenames to snake_case
I think this is out of date and in need of a rebase. Most of this is in master already (formatted and arranged differently)

2024-06-28 13:29 UTC, dc-mak commented on backend/cn/core_to_mucore.mli
> +  end
Sigh. [This is from Lem.](https://github.com/rems-project/lem/blob/master/ocaml-lib/pmap.ml). It's an old version of the OCaml Map module, before functorisation.

I don't know how much of this comes from Cerberus frontend, though I do think existing CN code should be transitioned to normal Stdlib Maps
```
13:49 ➜  cerberus git:(cn-tidying) ✗ grep "Pmap.empty" -R backend/cn
backend/cn/effectful.ml:        ) m (Pmap.empty cmp)
backend/cn/core_to_mucore.ml:      ) map (Pmap.empty compare)
backend/cn/core_to_mucore.ml:    fmap (Pmap.empty Sym.compare, [], false)
backend/cn/core_to_mucore.ml:          (Pmap.empty Int.compare,
backend/cn/core_to_mucore.ml:         ([], Pmap.empty Int.compare)
backend/cn/core_to_mucore.ml:    (return (Pmap.empty Sym.compare))
backend/cn/cLogicalFuns.ml:  let global_context = {label_defs = Pmap.empty Sym.compare; c_fun_pred_map; mu_call_funinfo} in
backend/cn/core_to_mucore.mli:                  ) map (Pmap.empty compare)
```

2024-07-19 17:43 UTC, bcpierce00 commented
It was too confusing to rebase the work here after all the incredibly many changes over the past couple of weeks, so I am going to just close this PR and open a new one starting from today's master branch.

2024-07-19 17:43 UTC, closed without merging